services:
  - type: web
    name: cognivita-apostilas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: ADMIN_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: ML_CLIENT_ID
        sync: false
      - key: ML_CLIENT_SECRET
        sync: false
      - key: ML_REDIRECT_URI
        sync: false
      - key: ML_CATEGORIA_ID
        value: MLB1227
      - key: PORT
        value: "8000"
